version: '3'
services:
  db:
    image: nouchka/sqlite3
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  railsgirls:
    build: .
    image: railsgirls
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/railsgirls
    ports:
      - "3000:3000"
    depends_on:
      - db
